// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currenciesData.proto

package com.maxsavteam.currencyconverterservice.protobuf;

public final class CurrenciesDataOuterClass {
  private CurrenciesDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CurrenciesDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>string language = 2;</code>
     * @return The language.
     */
    String getLanguage();
    /**
     * <code>string language = 2;</code>
     * @return The bytes for language.
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <pre>
     * contains pair code-name ("usd"-"U.S. dollar")
     * </pre>
     *
     * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
     */
    int getCurrenciesMapCount();
    /**
     * <pre>
     * contains pair code-name ("usd"-"U.S. dollar")
     * </pre>
     *
     * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
     */
    boolean containsCurrenciesMap(
        String key);
    /**
     * Use {@link #getCurrenciesMapMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getCurrenciesMap();
    /**
     * <pre>
     * contains pair code-name ("usd"-"U.S. dollar")
     * </pre>
     *
     * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
     */
    java.util.Map<String, String>
    getCurrenciesMapMap();
    /**
     * <pre>
     * contains pair code-name ("usd"-"U.S. dollar")
     * </pre>
     *
     * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
     */
    /* nullable */
String getCurrenciesMapOrDefault(
        String key,
        /* nullable */
String defaultValue);
    /**
     * <pre>
     * contains pair code-name ("usd"-"U.S. dollar")
     * </pre>
     *
     * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
     */
    String getCurrenciesMapOrThrow(
        String key);

    /**
     * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
     */
    java.util.List<CurrenciesData.Rate>
        getRatesList();
    /**
     * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
     */
    CurrenciesData.Rate getRates(int index);
    /**
     * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
     */
    int getRatesCount();
    /**
     * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
     */
    java.util.List<? extends CurrenciesData.RateOrBuilder>
        getRatesOrBuilderList();
    /**
     * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
     */
    CurrenciesData.RateOrBuilder getRatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData}
   */
  public static final class CurrenciesData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData)
      CurrenciesDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CurrenciesData.newBuilder() to construct.
    private CurrenciesData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CurrenciesData() {
      language_ = "";
      rates_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CurrenciesData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetCurrenciesMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CurrenciesData.class, Builder.class);
    }

    public interface RateOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string currencyName = 4;</code>
       * @return The currencyName.
       */
      String getCurrencyName();
      /**
       * <code>string currencyName = 4;</code>
       * @return The bytes for currencyName.
       */
      com.google.protobuf.ByteString
          getCurrencyNameBytes();

      /**
       * <code>map&lt;string, double&gt; ratesMap = 5;</code>
       */
      int getRatesMapCount();
      /**
       * <code>map&lt;string, double&gt; ratesMap = 5;</code>
       */
      boolean containsRatesMap(
          String key);
      /**
       * Use {@link #getRatesMapMap()} instead.
       */
      @Deprecated
      java.util.Map<String, Double>
      getRatesMap();
      /**
       * <code>map&lt;string, double&gt; ratesMap = 5;</code>
       */
      java.util.Map<String, Double>
      getRatesMapMap();
      /**
       * <code>map&lt;string, double&gt; ratesMap = 5;</code>
       */
      double getRatesMapOrDefault(
          String key,
          double defaultValue);
      /**
       * <code>map&lt;string, double&gt; ratesMap = 5;</code>
       */
      double getRatesMapOrThrow(
          String key);
    }
    /**
     * Protobuf type {@code com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate}
     */
    public static final class Rate extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate)
        RateOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Rate.newBuilder() to construct.
      private Rate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Rate() {
        currencyName_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new Rate();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      @Override
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetRatesMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Rate.class, Builder.class);
      }

      public static final int CURRENCYNAME_FIELD_NUMBER = 4;
      @SuppressWarnings("serial")
      private volatile Object currencyName_ = "";
      /**
       * <code>string currencyName = 4;</code>
       * @return The currencyName.
       */
      @Override
      public String getCurrencyName() {
        Object ref = currencyName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          currencyName_ = s;
          return s;
        }
      }
      /**
       * <code>string currencyName = 4;</code>
       * @return The bytes for currencyName.
       */
      @Override
      public com.google.protobuf.ByteString
          getCurrencyNameBytes() {
        Object ref = currencyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          currencyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int RATESMAP_FIELD_NUMBER = 5;
      private static final class RatesMapDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
            String, Double> defaultEntry =
                com.google.protobuf.MapEntry
                .<String, Double>newDefaultInstance(
                    CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_RatesMapEntry_descriptor,
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "",
                    com.google.protobuf.WireFormat.FieldType.DOUBLE,
                    0D);
      }
      @SuppressWarnings("serial")
      private com.google.protobuf.MapField<
          String, Double> ratesMap_;
      private com.google.protobuf.MapField<String, Double>
      internalGetRatesMap() {
        if (ratesMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              RatesMapDefaultEntryHolder.defaultEntry);
        }
        return ratesMap_;
      }
      public int getRatesMapCount() {
        return internalGetRatesMap().getMap().size();
      }
      /**
       * <code>map&lt;string, double&gt; ratesMap = 5;</code>
       */
      @Override
      public boolean containsRatesMap(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetRatesMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getRatesMapMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, Double> getRatesMap() {
        return getRatesMapMap();
      }
      /**
       * <code>map&lt;string, double&gt; ratesMap = 5;</code>
       */
      @Override
      public java.util.Map<String, Double> getRatesMapMap() {
        return internalGetRatesMap().getMap();
      }
      /**
       * <code>map&lt;string, double&gt; ratesMap = 5;</code>
       */
      @Override
      public double getRatesMapOrDefault(
          String key,
          double defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<String, Double> map =
            internalGetRatesMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, double&gt; ratesMap = 5;</code>
       */
      @Override
      public double getRatesMapOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<String, Double> map =
            internalGetRatesMap().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currencyName_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, currencyName_);
        }
        com.google.protobuf.GeneratedMessageV3
          .serializeStringMapTo(
            output,
            internalGetRatesMap(),
            RatesMapDefaultEntryHolder.defaultEntry,
            5);
        getUnknownFields().writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currencyName_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, currencyName_);
        }
        for (java.util.Map.Entry<String, Double> entry
             : internalGetRatesMap().getMap().entrySet()) {
          com.google.protobuf.MapEntry<String, Double>
          ratesMap__ = RatesMapDefaultEntryHolder.defaultEntry.newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
          size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(5, ratesMap__);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Rate)) {
          return super.equals(obj);
        }
        Rate other = (Rate) obj;

        if (!getCurrencyName()
            .equals(other.getCurrencyName())) return false;
        if (!internalGetRatesMap().equals(
            other.internalGetRatesMap())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CURRENCYNAME_FIELD_NUMBER;
        hash = (53 * hash) + getCurrencyName().hashCode();
        if (!internalGetRatesMap().getMap().isEmpty()) {
          hash = (37 * hash) + RATESMAP_FIELD_NUMBER;
          hash = (53 * hash) + internalGetRatesMap().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Rate parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Rate parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Rate parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Rate parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Rate parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Rate parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Rate parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Rate parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static Rate parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static Rate parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Rate parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Rate parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Rate prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate)
          RateOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
            int number) {
          switch (number) {
            case 5:
              return internalGetRatesMap();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
            int number) {
          switch (number) {
            case 5:
              return internalGetMutableRatesMap();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Rate.class, Builder.class);
        }

        // Construct using com.maxsavteam.currencyconverterservice.protobuf.CurrenciesDataOuterClass.CurrenciesData.Rate.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          currencyName_ = "";
          internalGetMutableRatesMap().clear();
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_descriptor;
        }

        @Override
        public Rate getDefaultInstanceForType() {
          return Rate.getDefaultInstance();
        }

        @Override
        public Rate build() {
          Rate result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public Rate buildPartial() {
          Rate result = new Rate(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(Rate result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.currencyName_ = currencyName_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.ratesMap_ = internalGetRatesMap();
            result.ratesMap_.makeImmutable();
          }
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Rate) {
            return mergeFrom((Rate)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Rate other) {
          if (other == Rate.getDefaultInstance()) return this;
          if (!other.getCurrencyName().isEmpty()) {
            currencyName_ = other.currencyName_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          internalGetMutableRatesMap().mergeFrom(
              other.internalGetRatesMap());
          bitField0_ |= 0x00000002;
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 34: {
                  currencyName_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 34
                case 42: {
                  com.google.protobuf.MapEntry<String, Double>
                  ratesMap__ = input.readMessage(
                      RatesMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                  internalGetMutableRatesMap().getMutableMap().put(
                      ratesMap__.getKey(), ratesMap__.getValue());
                  bitField0_ |= 0x00000002;
                  break;
                } // case 42
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private Object currencyName_ = "";
        /**
         * <code>string currencyName = 4;</code>
         * @return The currencyName.
         */
        public String getCurrencyName() {
          Object ref = currencyName_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            currencyName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string currencyName = 4;</code>
         * @return The bytes for currencyName.
         */
        public com.google.protobuf.ByteString
            getCurrencyNameBytes() {
          Object ref = currencyName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            currencyName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string currencyName = 4;</code>
         * @param value The currencyName to set.
         * @return This builder for chaining.
         */
        public Builder setCurrencyName(
            String value) {
          if (value == null) { throw new NullPointerException(); }
          currencyName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string currencyName = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearCurrencyName() {
          currencyName_ = getDefaultInstance().getCurrencyName();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string currencyName = 4;</code>
         * @param value The bytes for currencyName to set.
         * @return This builder for chaining.
         */
        public Builder setCurrencyNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          currencyName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private com.google.protobuf.MapField<
            String, Double> ratesMap_;
        private com.google.protobuf.MapField<String, Double>
            internalGetRatesMap() {
          if (ratesMap_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                RatesMapDefaultEntryHolder.defaultEntry);
          }
          return ratesMap_;
        }
        private com.google.protobuf.MapField<String, Double>
            internalGetMutableRatesMap() {
          if (ratesMap_ == null) {
            ratesMap_ = com.google.protobuf.MapField.newMapField(
                RatesMapDefaultEntryHolder.defaultEntry);
          }
          if (!ratesMap_.isMutable()) {
            ratesMap_ = ratesMap_.copy();
          }
          bitField0_ |= 0x00000002;
          onChanged();
          return ratesMap_;
        }
        public int getRatesMapCount() {
          return internalGetRatesMap().getMap().size();
        }
        /**
         * <code>map&lt;string, double&gt; ratesMap = 5;</code>
         */
        @Override
        public boolean containsRatesMap(
            String key) {
          if (key == null) { throw new NullPointerException("map key"); }
          return internalGetRatesMap().getMap().containsKey(key);
        }
        /**
         * Use {@link #getRatesMapMap()} instead.
         */
        @Override
        @Deprecated
        public java.util.Map<String, Double> getRatesMap() {
          return getRatesMapMap();
        }
        /**
         * <code>map&lt;string, double&gt; ratesMap = 5;</code>
         */
        @Override
        public java.util.Map<String, Double> getRatesMapMap() {
          return internalGetRatesMap().getMap();
        }
        /**
         * <code>map&lt;string, double&gt; ratesMap = 5;</code>
         */
        @Override
        public double getRatesMapOrDefault(
            String key,
            double defaultValue) {
          if (key == null) { throw new NullPointerException("map key"); }
          java.util.Map<String, Double> map =
              internalGetRatesMap().getMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, double&gt; ratesMap = 5;</code>
         */
        @Override
        public double getRatesMapOrThrow(
            String key) {
          if (key == null) { throw new NullPointerException("map key"); }
          java.util.Map<String, Double> map =
              internalGetRatesMap().getMap();
          if (!map.containsKey(key)) {
            throw new IllegalArgumentException();
          }
          return map.get(key);
        }
        public Builder clearRatesMap() {
          bitField0_ = (bitField0_ & ~0x00000002);
          internalGetMutableRatesMap().getMutableMap()
              .clear();
          return this;
        }
        /**
         * <code>map&lt;string, double&gt; ratesMap = 5;</code>
         */
        public Builder removeRatesMap(
            String key) {
          if (key == null) { throw new NullPointerException("map key"); }
          internalGetMutableRatesMap().getMutableMap()
              .remove(key);
          return this;
        }
        /**
         * Use alternate mutation accessors instead.
         */
        @Deprecated
        public java.util.Map<String, Double>
            getMutableRatesMap() {
          bitField0_ |= 0x00000002;
          return internalGetMutableRatesMap().getMutableMap();
        }
        /**
         * <code>map&lt;string, double&gt; ratesMap = 5;</code>
         */
        public Builder putRatesMap(
            String key,
            double value) {
          if (key == null) { throw new NullPointerException("map key"); }

          internalGetMutableRatesMap().getMutableMap()
              .put(key, value);
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>map&lt;string, double&gt; ratesMap = 5;</code>
         */
        public Builder putAllRatesMap(
            java.util.Map<String, Double> values) {
          internalGetMutableRatesMap().getMutableMap()
              .putAll(values);
          bitField0_ |= 0x00000002;
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate)
      }

      // @@protoc_insertion_point(class_scope:com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate)
      private static final Rate DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Rate();
      }

      public static Rate getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Rate>
          PARSER = new com.google.protobuf.AbstractParser<Rate>() {
        @Override
        public Rate parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Rate> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Rate> getParserForType() {
        return PARSER;
      }

      @Override
      public Rate getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_ = 0L;
    /**
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int LANGUAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object language_ = "";
    /**
     * <code>string language = 2;</code>
     * @return The language.
     */
    @Override
    public String getLanguage() {
      Object ref = language_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <code>string language = 2;</code>
     * @return The bytes for language.
     */
    @Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCIESMAP_FIELD_NUMBER = 3;
    private static final class CurrenciesMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_CurrenciesMapEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        String, String> currenciesMap_;
    private com.google.protobuf.MapField<String, String>
    internalGetCurrenciesMap() {
      if (currenciesMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CurrenciesMapDefaultEntryHolder.defaultEntry);
      }
      return currenciesMap_;
    }
    public int getCurrenciesMapCount() {
      return internalGetCurrenciesMap().getMap().size();
    }
    /**
     * <pre>
     * contains pair code-name ("usd"-"U.S. dollar")
     * </pre>
     *
     * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
     */
    @Override
    public boolean containsCurrenciesMap(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetCurrenciesMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCurrenciesMapMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getCurrenciesMap() {
      return getCurrenciesMapMap();
    }
    /**
     * <pre>
     * contains pair code-name ("usd"-"U.S. dollar")
     * </pre>
     *
     * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
     */
    @Override
    public java.util.Map<String, String> getCurrenciesMapMap() {
      return internalGetCurrenciesMap().getMap();
    }
    /**
     * <pre>
     * contains pair code-name ("usd"-"U.S. dollar")
     * </pre>
     *
     * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
     */
    @Override
    public /* nullable */
String getCurrenciesMapOrDefault(
        String key,
        /* nullable */
String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetCurrenciesMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * contains pair code-name ("usd"-"U.S. dollar")
     * </pre>
     *
     * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
     */
    @Override
    public String getCurrenciesMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetCurrenciesMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int RATES_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private java.util.List<Rate> rates_;
    /**
     * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
     */
    @Override
    public java.util.List<Rate> getRatesList() {
      return rates_;
    }
    /**
     * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
     */
    @Override
    public java.util.List<? extends RateOrBuilder>
        getRatesOrBuilderList() {
      return rates_;
    }
    /**
     * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
     */
    @Override
    public int getRatesCount() {
      return rates_.size();
    }
    /**
     * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
     */
    @Override
    public Rate getRates(int index) {
      return rates_.get(index);
    }
    /**
     * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
     */
    @Override
    public RateOrBuilder getRatesOrBuilder(
        int index) {
      return rates_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeUInt64(1, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, language_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetCurrenciesMap(),
          CurrenciesMapDefaultEntryHolder.defaultEntry,
          3);
      for (int i = 0; i < rates_.size(); i++) {
        output.writeMessage(6, rates_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, language_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetCurrenciesMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        currenciesMap__ = CurrenciesMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, currenciesMap__);
      }
      for (int i = 0; i < rates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, rates_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CurrenciesData)) {
        return super.equals(obj);
      }
      CurrenciesData other = (CurrenciesData) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (!internalGetCurrenciesMap().equals(
          other.internalGetCurrenciesMap())) return false;
      if (!getRatesList()
          .equals(other.getRatesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      if (!internalGetCurrenciesMap().getMap().isEmpty()) {
        hash = (37 * hash) + CURRENCIESMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCurrenciesMap().hashCode();
      }
      if (getRatesCount() > 0) {
        hash = (37 * hash) + RATES_FIELD_NUMBER;
        hash = (53 * hash) + getRatesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CurrenciesData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CurrenciesData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CurrenciesData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CurrenciesData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CurrenciesData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CurrenciesData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CurrenciesData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CurrenciesData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CurrenciesData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CurrenciesData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CurrenciesData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CurrenciesData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CurrenciesData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData)
        CurrenciesDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetCurrenciesMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableCurrenciesMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CurrenciesData.class, Builder.class);
      }

      // Construct using com.maxsavteam.currencyconverterservice.protobuf.CurrenciesDataOuterClass.CurrenciesData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = 0L;
        language_ = "";
        internalGetMutableCurrenciesMap().clear();
        if (ratesBuilder_ == null) {
          rates_ = java.util.Collections.emptyList();
        } else {
          rates_ = null;
          ratesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CurrenciesDataOuterClass.internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_descriptor;
      }

      @Override
      public CurrenciesData getDefaultInstanceForType() {
        return CurrenciesData.getDefaultInstance();
      }

      @Override
      public CurrenciesData build() {
        CurrenciesData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CurrenciesData buildPartial() {
        CurrenciesData result = new CurrenciesData(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(CurrenciesData result) {
        if (ratesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            rates_ = java.util.Collections.unmodifiableList(rates_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.rates_ = rates_;
        } else {
          result.rates_ = ratesBuilder_.build();
        }
      }

      private void buildPartial0(CurrenciesData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.language_ = language_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.currenciesMap_ = internalGetCurrenciesMap();
          result.currenciesMap_.makeImmutable();
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CurrenciesData) {
          return mergeFrom((CurrenciesData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CurrenciesData other) {
        if (other == CurrenciesData.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        internalGetMutableCurrenciesMap().mergeFrom(
            other.internalGetCurrenciesMap());
        bitField0_ |= 0x00000004;
        if (ratesBuilder_ == null) {
          if (!other.rates_.isEmpty()) {
            if (rates_.isEmpty()) {
              rates_ = other.rates_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureRatesIsMutable();
              rates_.addAll(other.rates_);
            }
            onChanged();
          }
        } else {
          if (!other.rates_.isEmpty()) {
            if (ratesBuilder_.isEmpty()) {
              ratesBuilder_.dispose();
              ratesBuilder_ = null;
              rates_ = other.rates_;
              bitField0_ = (bitField0_ & ~0x00000008);
              ratesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRatesFieldBuilder() : null;
            } else {
              ratesBuilder_.addAllMessages(other.rates_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                language_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<String, String>
                currenciesMap__ = input.readMessage(
                    CurrenciesMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableCurrenciesMap().getMutableMap().put(
                    currenciesMap__.getKey(), currenciesMap__.getValue());
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 50: {
                Rate m =
                    input.readMessage(
                        Rate.parser(),
                        extensionRegistry);
                if (ratesBuilder_ == null) {
                  ensureRatesIsMutable();
                  rates_.add(m);
                } else {
                  ratesBuilder_.addMessage(m);
                }
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object language_ = "";
      /**
       * <code>string language = 2;</code>
       * @return The language.
       */
      public String getLanguage() {
        Object ref = language_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string language = 2;</code>
       * @return The bytes for language.
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string language = 2;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        language_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string language = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        language_ = getDefaultInstance().getLanguage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string language = 2;</code>
       * @param value The bytes for language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        language_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> currenciesMap_;
      private com.google.protobuf.MapField<String, String>
          internalGetCurrenciesMap() {
        if (currenciesMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CurrenciesMapDefaultEntryHolder.defaultEntry);
        }
        return currenciesMap_;
      }
      private com.google.protobuf.MapField<String, String>
          internalGetMutableCurrenciesMap() {
        if (currenciesMap_ == null) {
          currenciesMap_ = com.google.protobuf.MapField.newMapField(
              CurrenciesMapDefaultEntryHolder.defaultEntry);
        }
        if (!currenciesMap_.isMutable()) {
          currenciesMap_ = currenciesMap_.copy();
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return currenciesMap_;
      }
      public int getCurrenciesMapCount() {
        return internalGetCurrenciesMap().getMap().size();
      }
      /**
       * <pre>
       * contains pair code-name ("usd"-"U.S. dollar")
       * </pre>
       *
       * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
       */
      @Override
      public boolean containsCurrenciesMap(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetCurrenciesMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCurrenciesMapMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, String> getCurrenciesMap() {
        return getCurrenciesMapMap();
      }
      /**
       * <pre>
       * contains pair code-name ("usd"-"U.S. dollar")
       * </pre>
       *
       * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
       */
      @Override
      public java.util.Map<String, String> getCurrenciesMapMap() {
        return internalGetCurrenciesMap().getMap();
      }
      /**
       * <pre>
       * contains pair code-name ("usd"-"U.S. dollar")
       * </pre>
       *
       * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
       */
      @Override
      public /* nullable */
String getCurrenciesMapOrDefault(
          String key,
          /* nullable */
String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<String, String> map =
            internalGetCurrenciesMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * contains pair code-name ("usd"-"U.S. dollar")
       * </pre>
       *
       * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
       */
      @Override
      public String getCurrenciesMapOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<String, String> map =
            internalGetCurrenciesMap().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearCurrenciesMap() {
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableCurrenciesMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * contains pair code-name ("usd"-"U.S. dollar")
       * </pre>
       *
       * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
       */
      public Builder removeCurrenciesMap(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableCurrenciesMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
          getMutableCurrenciesMap() {
        bitField0_ |= 0x00000004;
        return internalGetMutableCurrenciesMap().getMutableMap();
      }
      /**
       * <pre>
       * contains pair code-name ("usd"-"U.S. dollar")
       * </pre>
       *
       * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
       */
      public Builder putCurrenciesMap(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableCurrenciesMap().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * contains pair code-name ("usd"-"U.S. dollar")
       * </pre>
       *
       * <code>map&lt;string, string&gt; currenciesMap = 3;</code>
       */
      public Builder putAllCurrenciesMap(
          java.util.Map<String, String> values) {
        internalGetMutableCurrenciesMap().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }

      private java.util.List<Rate> rates_ =
        java.util.Collections.emptyList();
      private void ensureRatesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          rates_ = new java.util.ArrayList<Rate>(rates_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Rate, Rate.Builder, RateOrBuilder> ratesBuilder_;

      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public java.util.List<Rate> getRatesList() {
        if (ratesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rates_);
        } else {
          return ratesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public int getRatesCount() {
        if (ratesBuilder_ == null) {
          return rates_.size();
        } else {
          return ratesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Rate getRates(int index) {
        if (ratesBuilder_ == null) {
          return rates_.get(index);
        } else {
          return ratesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Builder setRates(
          int index, Rate value) {
        if (ratesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatesIsMutable();
          rates_.set(index, value);
          onChanged();
        } else {
          ratesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Builder setRates(
          int index, Rate.Builder builderForValue) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.set(index, builderForValue.build());
          onChanged();
        } else {
          ratesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Builder addRates(Rate value) {
        if (ratesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatesIsMutable();
          rates_.add(value);
          onChanged();
        } else {
          ratesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Builder addRates(
          int index, Rate value) {
        if (ratesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatesIsMutable();
          rates_.add(index, value);
          onChanged();
        } else {
          ratesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Builder addRates(
          Rate.Builder builderForValue) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.add(builderForValue.build());
          onChanged();
        } else {
          ratesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Builder addRates(
          int index, Rate.Builder builderForValue) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.add(index, builderForValue.build());
          onChanged();
        } else {
          ratesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Builder addAllRates(
          Iterable<? extends Rate> values) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rates_);
          onChanged();
        } else {
          ratesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Builder clearRates() {
        if (ratesBuilder_ == null) {
          rates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          ratesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Builder removeRates(int index) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.remove(index);
          onChanged();
        } else {
          ratesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Rate.Builder getRatesBuilder(
          int index) {
        return getRatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public RateOrBuilder getRatesOrBuilder(
          int index) {
        if (ratesBuilder_ == null) {
          return rates_.get(index);  } else {
          return ratesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public java.util.List<? extends RateOrBuilder>
           getRatesOrBuilderList() {
        if (ratesBuilder_ != null) {
          return ratesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rates_);
        }
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Rate.Builder addRatesBuilder() {
        return getRatesFieldBuilder().addBuilder(
            Rate.getDefaultInstance());
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public Rate.Builder addRatesBuilder(
          int index) {
        return getRatesFieldBuilder().addBuilder(
            index, Rate.getDefaultInstance());
      }
      /**
       * <code>repeated .com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData.Rate rates = 6;</code>
       */
      public java.util.List<Rate.Builder>
           getRatesBuilderList() {
        return getRatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Rate, Rate.Builder, RateOrBuilder>
          getRatesFieldBuilder() {
        if (ratesBuilder_ == null) {
          ratesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Rate, Rate.Builder, RateOrBuilder>(
                  rates_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          rates_ = null;
        }
        return ratesBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData)
    }

    // @@protoc_insertion_point(class_scope:com.maxsavteam.currencyconverterservice.protobuf.CurrenciesData)
    private static final CurrenciesData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CurrenciesData();
    }

    public static CurrenciesData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CurrenciesData>
        PARSER = new com.google.protobuf.AbstractParser<CurrenciesData>() {
      @Override
      public CurrenciesData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CurrenciesData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CurrenciesData> getParserForType() {
      return PARSER;
    }

    @Override
    public CurrenciesData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_CurrenciesMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_CurrenciesMapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_RatesMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_RatesMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024currenciesData.proto\0220com.maxsavteam.c" +
      "urrencyconverterservice.protobuf\"\344\003\n\016Cur" +
      "renciesData\022\021\n\ttimestamp\030\001 \001(\004\022\020\n\010langua" +
      "ge\030\002 \001(\t\022j\n\rcurrenciesMap\030\003 \003(\0132S.com.ma" +
      "xsavteam.currencyconverterservice.protob" +
      "uf.CurrenciesData.CurrenciesMapEntry\022T\n\005" +
      "rates\030\006 \003(\0132E.com.maxsavteam.currencycon" +
      "verterservice.protobuf.CurrenciesData.Ra" +
      "te\0324\n\022CurrenciesMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\t:\0028\001\032\264\001\n\004Rate\022\024\n\014currencyNam" +
      "e\030\004 \001(\t\022e\n\010ratesMap\030\005 \003(\0132S.com.maxsavte" +
      "am.currencyconverterservice.protobuf.Cur" +
      "renciesData.Rate.RatesMapEntry\032/\n\rRatesM" +
      "apEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\001:\0028\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_descriptor,
        new String[] { "Timestamp", "Language", "CurrenciesMap", "Rates", });
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_CurrenciesMapEntry_descriptor =
      internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_descriptor.getNestedTypes().get(0);
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_CurrenciesMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_CurrenciesMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_descriptor =
      internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_descriptor.getNestedTypes().get(1);
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_descriptor,
        new String[] { "CurrencyName", "RatesMap", });
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_RatesMapEntry_descriptor =
      internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_descriptor.getNestedTypes().get(0);
    internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_RatesMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_maxsavteam_currencyconverterservice_protobuf_CurrenciesData_Rate_RatesMapEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
